title = "Kerem Bozdas"
email = "kerem@kerembozdas.com"
url = "https://blog.kerembozdas.com"
description = "Personal blog"
show_excerpts = true
remote_theme = "jekyll/minima"
plugins = [
  "jekyll-asciidoc",
  "jekyll-compose",
  "jekyll-feed",
  "jekyll-remote-theme",
]

[minima]
skin = "auto"
date_format = "%b %-d, %Y"

[asciidoctor]
attributes = [
  "idprefix=_",
  "source-highlighter=pygments",
  "pygments-stylesheet!",
]

[jekyll_compose]
auto_open = true

[jekyll_compose.default_front_matter.posts]
description = "TODO: Add description"
published = true
sitemap = true
