title = "Kerem Bozdas"
email = "kerem@kerembozdas.com"
description = "Personal blog of Kerem Bozdas"
baseurl = ""
url = "https://blog.kerembozdas.com"
github_username = "krmbzds"
remote_theme = "jekyll/minima"
plugins = [
  "jekyll-asciidoc",
  "jekyll-compose",
  "jekyll-feed",
  "jekyll-remote-theme",
]

[minima]
skin = "auto"

[asciidoctor]
attributes = [
  "idprefix=_",
  "source-highlighter=pygments",
  "pygments-stylesheet!",
]

[jekyll_compose]
auto_open = true

[jekyll_compose.default_front_matter.posts]
description = "TODO: Add description"
published = true
sitemap = true
