title: Kerem Bozdas
email: kerem@kerembozdas.com
description: Personal blog of Kerem Bozdas
baseurl: ""
url: "https://blog.kerembozdas.com"
github_username: krmbzds
remote_theme: jekyll/minima
minima:
  skin: auto
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-remote-theme
